### PR TITLE
using git tag to fetch tags instead of git log

### PR DESCRIPTION
**Pull request by pjpsoares**

### CODE REVIEW

**Comment by stevemao** [comment]
Tests failed. Any idea why?

**Comment by pjpsoares** [comment]
Git version?

**Comment by pjpsoares** [comment]
Reading the travis docs http://docs.travis-ci.com/user/ci-environment/ it should come bundled with 1.8, but it uses the PPA that should update it to 2.5 (I think). Can you try using the before_install on travis to do apt_get update or use apt_get to fetch the correct git version?

**Comment by stevemao** [comment]
I tested manually, this does not keep tags in order.

**Comment by stevemao** [comment]
I'm closing this now as this does not produce the correct order

**Pull request closed without merging**
